// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderManagementAPI.Models;

public partial class Cliente
{
    public long ClienteId { get; set; }

    public string Nombre { get; set; }

    public string Identidad { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Orden> Ordens { get; set; } = new List<Orden>();
}